version: '3'


services:
  sql:
    container_name: fastapi-sql
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USERNAME=${DB_USERNAME}
      - TZ=Asia/Seoul
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-server=utf8mb4
      - --lower_case_table_names=1
    # volumes:
    #   - mysql_data:/var/lib/mysql